name: GetFbKeyHash
on: push

jobs:
  build:
    name: release
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, 'keyhash')"
    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: get key hash
      env:
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      run: |
        export keyHash=$(keytool -exportcert -alias ${{ env.RELEASE_KEY_ALIAS }} -keystore ./test.jks -storepass ${{ env.RELEASE_KEY_PASSWORD }} | openssl sha1 -binary | openssl base64)
        echo "::set-env name=keyHash::$keyHash"
    - name: print key hash
      run: echo ${keyHash}
